<?php

namespace Bodu\ContactLinkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactLinkRepository extends EntityRepository
{
    public function getMaxRank()
    {
        try
        {
            $query = $this->_em->createQuery('SELECT MAX(cl.rank) FROM BoduContactLinkBundle:ContactLink cl');
            return $query->getSingleScalarResult();
        }
        catch (Exception $ex) {
            return '1';
        }
    }
}
