parameters:
#    bodu_section.example.class: Bodu\SectionBundle\Example

services:
#    bodu_section.example:
#        class: %bodu_section.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
