security:
    encoders:
        Symfony\Component\Security\Core\User\User: md5

    role_hierarchy:
        ROLE_ADMIN: ROLE_ADMIN

    providers:
        admin_provider:
            memory:
                users:
                    test: { password: GFDSJF7fSDF7sdfs96v==, roles: [ 'ROLE_ADMIN' ] }
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        resources:
            pattern:  ^/resources
            security: false
        main:
            pattern:  ^/
            anonymous: true
            provider: admin_provider
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
