bodu_contact_link_fo:
    path:  /contact
    defaults: { _controller: "BoduContactLinkBundle:ContactFO:display" }

bodu_contact_link_bo_list:
    path:  /admin/contactLink/list
    defaults: { _controller: "BoduContactLinkBundle:ContactLinkBO:listContactLink" }

bodu_contact_link_bo_edit:
    path:  /admin/contactLink/edit/{id}
    defaults: { _controller: "BoduContactLinkBundle:ContactLinkBO:editContactLink", id: 0 }

bodu_contact_link_bo_delete:
    path:  /admin/contactLink/delete/{id}
    defaults: { _controller: "BoduContactLinkBundle:ContactLinkBO:deleteContactLink" }
    requirements:
        id: \d+
