<?php

namespace Bodu\VideoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository
{
    public function getMaxRank()
    {
        try
        {
            $query = $this->_em->createQuery('SELECT MAX(v.rank) FROM BoduVideoBundle:Video v');
            return $query->getSingleScalarResult();
        }
        catch (Exception $ex) {
            return '1';
        }
    }
}
