parameters:
#    bodu_skin.example.class: Bodu\SkinBundle\Example

services:
#    bodu_skin.example:
#        class: %bodu_skin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
