<?php

namespace Bodu\SlideshowBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SlideshowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlideshowRepository extends EntityRepository
{
    public function getMaxRank()
    {
        try
        {
            $query = $this->_em->createQuery('SELECT MAX(s.rank) FROM BoduSlideshowBundle:Slideshow s');
            return $query->getSingleScalarResult();
        }
        catch (Exception $ex) {
            return '1';
        }
    }

    public function searchSlideshow($sectionName, $sectionId)
    {
        try
        {
            $queryBuilder = $this->_em->createQueryBuilder();
            $queryBuilder->select('sl')
                    ->from('BoduSlideshowBundle:Slideshow', 'sl');

            if ($sectionId != 0)
            {
                $queryBuilder->leftJoin('sl.section', 'se');

                // Condition with no section at all
                if ($sectionId == -1)
                    $queryBuilder->where('se IS NULL');
                // Condition with specific section
                else
                    $queryBuilder->where('se.id = :sectionId')->setParameter('sectionId', $sectionId);
            }

            if (strlen($sectionName) > 0)
                $queryBuilder->andwhere('sl.name LIKE :sectionName')->setParameter('sectionName', '%' . $sectionName . '%');

            return $queryBuilder->getQuery()->getResult();
        }
        catch (Exception $ex) {
            return array();
        }
    }
}
