parameters:
#    bodu_news.example.class: Bodu\NewsBundle\Example

services:
#    bodu_news.example:
#        class: %bodu_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
