bodu_video_fo:
    path:  /videos
    defaults: { _controller: "BoduVideoBundle:VideoFO:display" }

bodu_video_bo_list:
    path:  /admin/video/list
    defaults: { _controller: "BoduVideoBundle:VideoBO:listVideo" }

bodu_video_bo_edit:
    path:  /admin/video/edit/{id}
    defaults: { _controller: "BoduVideoBundle:VideoBO:editVideo", id: 0 }

bodu_video_bo_delete:
    path:  /admin/video/delete/{id}
    defaults: { _controller: "BoduVideoBundle:VideoBO:deleteVideo" }
    requirements:
        id: \d+
