parameters:
#    bodu_video.example.class: Bodu\VideoBundle\Example

services:
#    bodu_video.example:
#        class: %bodu_video.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
