Bodu\VideoBundle\Entity\Video:
    properties:
        name:
            - NotBlank: 
                 message: "Ce champ est obligatoire"
        videoIntegration:
            - NotBlank: 
                 message: "Ce champ est obligatoire"
